


### POST 
POST http://localhost:8888/roles/createOne
Content-Type: application/json

{
    "title": "autre role"
}


### GET all 
GET http://localhost:8888/roles/getAll

### GET one 
GET http://localhost:8888/roles/getOne/1

### PUT 
PUT http://localhost:8888/roles/updateOne/2
Content-Type: application/json

{
    "title": "agahaha"
}

### DELETE 
DELETE http://localhost:8888/roles/deleteOne/1