### POST

POST http://localhost:8888/orders/createOne
Content-Type: application/json

{
    "totalHT": 12120.01,
    "totalTTC": 1258984.20,
    "tax": 125.02,
    "quantity": 5,
    "user_id": 1,
    "order_states_id": 1
}

### POST

POST http://localhost:8888/orderProduct/createOne
Content-Type: application/json

{
    "product_id": 1,
    "order_id": 4,
    "quantity": 5,
    "priceHT": 12.30,
    "TVA": "20%"
}


### PUT
PUT http://localhost:8888/categories/updateOnePut/14
Content-Type: application/json

{
    "title": "",
    "active": "false"
}

### PATCH
PATCH http://localhost:8888/categories/updateOnePatch/14
Content-Type: application/json

{
    "active": "true"
}


###
POST http://localhost:8888/orderProduct/createOne
Content-Type: application/json

{
    "product_id": 2,
    "order_id": 4,
    "quantity": 2,
    "priceHT": 1253.02,
    "TVA": "20%"
}


###
POST http://localhost:8888/orderProduct/createOne
Content-Type: application/json

{
    "product_id": 1,
    "order_id": 1,
    "quantity": 1,
    "priceHT": 12550,
    "TVA": "20%"
}

###

POST http://localhost:8888/orderTypeAdress/createOne
Content-Type: application/json

{
    "order_id": 4,
    "adress_id": 3,
    "adress_type_id": 1
}


###

PUT http://localhost:8888/categories/updateOnePut/14
Content-Type: application/json

{
    "title": "encore un essai"
}

###

PATCH http://localhost:8888/adresses/updateOnePatch/3
Content-Type: application/json

{
    "entitled": "Marie"
}


### 
POST http://localhost:8888/users/createOne
Content-Type: application/json

{
    "title": "test"
}

###
GET http://localhost:8888/users/getOne/1

###
POST http://localhost:8888/users/createOne 
Content-Type: application/json

{
    "firstname": "Ma",
    "lastname": "Lou-ledd",
    "password": "Cou.123458",
    "role_id": 2,
    "email": "admin@gmil.com"
}



###
POST http://localhost:8888/categories/createOne
Content-Type: application/json

{
    "title": "Phone"
}

### 
DELETE http://localhost:8888/orderTypeAdress/deleteOne
Content-Type: application/json

{
    "order_id": 4,
    "adress_id": 3,
    "adress_type_id": 1
}


### 
POST http://localhost:8888/orderTypeAdress/createOne
Content-Type: application/json

{
    "order_id": 4,
    "adress_id": 3,
    "adress_type_id": 1
}


###
POST http://localhost:8888/users/login
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "password"
}

{
    "email": "example@example.com",
    "password": "password"
}


